# Generated by Django 5.1.4 on 2024-12-25 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerKeyPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('private_key', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='File_app_se_is_acti_95b934_idx')],
            },
        ),
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('encrypted_data', models.BinaryField()),
                ('client_iv', models.BinaryField()),
                ('server_iv', models.BinaryField()),
                ('server_key', models.BinaryField()),
                ('client_key', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='File_app_en_user_id_27fb29_idx'), models.Index(fields=['filename'], name='File_app_en_filenam_f8cc09_idx')],
            },
        ),
    ]
