# Generated by Django 5.1.4 on 2024-12-26 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('download_permission', models.ManyToManyField(related_name='downloadable_files', to=settings.AUTH_USER_MODEL)),
                ('encrypted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='File_app.encryptedfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL)),
                ('view_permission', models.ManyToManyField(related_name='viewable_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
