# Generated by Django 5.1.4 on 2024-12-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File_app', '0002_sharedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfile',
            old_name='encrypted_file',
            new_name='file_id',
        ),
    ]
