# Generated by Django 5.1.4 on 2024-12-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File_app', '0003_rename_encrypted_file_sharedfile_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfile',
            old_name='file_id',
            new_name='encrypted_file_id',
        ),
    ]
