# Generated by Django 5.1.4 on 2024-12-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File_app', '0004_rename_file_id_sharedfile_encrypted_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfile',
            old_name='encrypted_file_id',
            new_name='encrypted_file',
        ),
    ]
