# Generated by Django 5.1.4 on 2024-12-27 00:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_app', '0005_rename_encrypted_file_id_sharedfile_encrypted_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareableLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('access_key', models.BinaryField()),
                ('max_downloads', models.IntegerField(null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='File_app.encryptedfile')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'is_active'], name='File_app_sh_expires_cfd339_idx'), models.Index(fields=['file', 'created_at'], name='File_app_sh_file_id_9d8383_idx')],
            },
        ),
    ]
