# Generated by Django 5.1.4 on 2024-12-27 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('File_app', '0006_shareablelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareablelink',
            name='access_key',
        ),
    ]
