# Generated by Django 5.1.4 on 2024-12-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
