# Generated by Django 5.1.4 on 2024-12-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
